export const MARKETING_PARAMETERS = [
  // UTM / GA4
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'utm_id',
  // Ads click IDs
  'gclid',
  'gclsrc',
  'dclid',
  'gbraid',
  'wbraid',
  'fbclid',
  'msclkid',
  'ttclid',
  'twclid',
  'yclid',
  'yadclid',
  'ysclid',
  'li_fat_id',
  // Marketing-automation / CRM
  'hsa_acc',
  'hsa_cam',
  'hsa_grp',
  'hsa_ad',
  'hsa_src',
  'hsa_net',
  'hsa_ver',
  '_hsenc',
  '_hsmi',
  '__hssc',
  '__hstc',
  'hsCtaTracking',
  'mkt_tok',
  'mc_cid',
  'mc_eid',
  'mc_tc',
  // Self-hosted Analytics
  'pk_campaign',
  'pk_kwd',
  'mtm_campaign',
  'mtm_kwd',
];
