name: Build Browser Extensions

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Chrome/Edge Extension
        run: yarn build:chrome-edge

      - name: Build Firefox Extension
        run: yarn build:firefox

      - name: Zip Chrome/Edge extension
        run: zip -r dist/extension-chrome-edge.zip dist_chrome_edge

      - name: Zip Firefox extension
        run: zip -r dist/extension-firefox.zip dist_firefox

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: browser-extensions
          path: |
            dist/extension-chrome-edge.zip
            dist/extension-firefox.zip
